### ISSUE TITLE
Why is the rdf loading broken?

### ISSUE THREAD

**Issue by NanderTGA** [GittyMac/OpenFK#1]
I just looked at the broken things, realizing the rdf loading is broken.
Why is it broken?
Or is it just not implemented yet?
I can help translating [the rdf util](https://www.reddit.com/r/UBFunkeys/comments/9z2mzk/ubfunkeys_rdf_util/) if you want from java to c#.

**Comment by GittyMac** [comment]
It's not implemented yet. I'm working on a C# port of the RDF utility which will be adapted into OpenFK soon.

**Comment by NanderTGA** [comment]
ok

**Comment by NanderTGA** [comment]
reopen, close, reopen, close
