### ISSUE TITLE
fix: detect older FSGUI versions and missing update files

### ISSUE THREAD

**Issue by NanderTGA** [GittyMac/OpenFK#9]
I've noticed some people still manage to find older versions of OpenFK and FSGUI, back when it was called FunkeySelector.
The version of OpenFK doesn't seem too old because it still auto-updates, but FSGUI doesn't, because the older version is named `FunkeySelector.exe` and not `FunkeySelectorGUI.exe`, which is what OpenFK checks for.

We should ensure the following is dealt with:
- A missing `fsguiupdate.xml`
- Older `FunkeySelector.exe`
- Where people keep finding these old downloads

**Comment by NanderTGA** [comment]
Turns out the guide has at least one link with an older version of fsgui
Here's one I found to have one: [U.B. Funkeys 5.0 Full Game with No Hub & Funkey Select](https://www.mediafire.com/file/d2yqpuei0ic124j/U.B._Funkeys_5.0_with_No_Hub_and_Funkey_Select.zip/file) (Zipped folder)

**Comment by GittyMac** [comment]
The third part of the issue is out of the scope of OpenFK, but the first two concerns are handled with the new UpdateManager in cce4de1.

**Comment by NanderTGA** [comment]
The third part won't be a problem for very long, but I think we should check for a `FunkeySelector.exe` file on start and mess with `options.rdf` so it will check for updates incase it finds the file, so users don't notice the old one and can just play.
I think we should also add a button in the options menu to trigger this tampering with `options.rdf` to trigger an update.
